version: '3.9'
services:

  scrape-goodreads:
    # restart: unless-stopped
    image: scrapy-env
    container_name: scrape-goodreads
    # network_mode:  host
    command:
            - /bin/bash
            - -c
            - |
              cd /mnt_src
              scrapy crawl \
                --logfile=scrapy.log \
                -a start_page_no=26 \
                -a end_page_no=600 \
                -a list_name="1.Best_Books_Ever" \
                -s OUTPUT_FILE_SUFFIX="best_026_600" \
                list

    # ports:
    #  - "5555:5555"
    # environment:
    #  - AM_I_IN_A_DOCKER_CONTAINER=Yes
    #  - GOOGLE_APPLICATION_CREDENTIALS=/root/google_config/service-account-file.json
    volumes:
     - /home/${USER}/repos/GoodreadsScraper:/mnt_src