version: '3.9'
services:

  scrape-goodreads:
    # restart: unless-stopped
    image: scrapy-env
    container_name: scrape-goodreads
    # network_mode:  host
    command:
            - /bin/bash
            - -c
            - |
              cd /mnt_src
              python lightgbm-train.py
              # python -c 'while 1: pass'

    # ports:
    #  - "5555:5555"
    # environment:
    #  - AM_I_IN_A_DOCKER_CONTAINER=Yes
    #  - GOOGLE_APPLICATION_CREDENTIALS=/root/google_config/service-account-file.json
    volumes:
     - /home/${USER}/repos/GoodreadsScraper:/mnt_src