version: '3.9'
services:

  scrape-goodreads:
    # restart: unless-stopped
    image: scrapy-env
    container_name: scrape-goodreads
    # network_mode:  host
    environment:
     - LIST_TO_SCRAPE=79365.Favorite_herbal_natural_health_books
     - OUTPUT_FILE_SUFFIX=best_herbal_books
    command:
            - /bin/bash
            - -c
            - |
              cd /mnt_src
              scrapy crawl \
                --logfile=scrapy.log \
                -a start_page_no=1 \
                -a end_page_no=2 \
                -a list_name=$${LIST_TO_SCRAPE} \
                -s OUTPUT_FILE_SUFFIX=$${OUTPUT_FILE_SUFFIX} \
                list

    # ports:
    #  - "5555:5555"
     # - LIST_TO_SCRAPE="1.Best_Books_Ever"
     # - OUTPUT_FILE_SUFFIX="best_001_700"
     # - AM_I_IN_A_DOCKER_CONTAINER=Yes
    volumes:
     - /home/${USER}/repos/GoodreadsScraper:/mnt_src